version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: tni_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - tni_pgdata:/var/lib/postgresql
volumes:
  tni_pgdata: